export interface IQirForm {
  createdBy: string;
  completedBy: string;
  qir: string;
  capaId: string;
  type: string;
  type1: string;
  stakeholder: string;
  owner: string;
  priority: string;
  createdDate: string;
  active: number;
  status: string;
  issueComment: string;
  issue_comment_html: string;
  verifiedBy: string;
  customerName: string;
  purchaseOrder: string;
  CustomerPartNumber: string;
  eyefiPartNumber: string;
  confirmationCode: string
  firstName: string;
  lastName: string;
  source: string;
  failureType: string;
  qtyAffected: string;
  qtyAffected1: string;
  customerReportedDate: string;
  componentType: string;
  platformType: string;
  qaComments: string;
  supplierName: string;
  casinoName: string;
  typeSub: string;
  eyefiSerialNumber: string;
  fieldServiceSchedulerId: number;
  lotNumber: string;
  first_name: string;
  last_name: string;
  email: string;
  customerSerialNumber?: string
  location?: string
}
