export interface ScheduledJobDefinition {
  id: string;
  name: string;
  cron: string;
  url: string;
  active: boolean;
  note?: string;
}

export const SCHEDULED_JOBS_TIMEZONE = 'America/Los_Angeles';

export const SCHEDULED_JOB_DEFINITIONS: ScheduledJobDefinition[] = [
  {
    id: 'menu-badge-cache-refresh',
    name: 'Menu Badge Cache Refresh',
    cron: '0 0 * * * *',
    url: 'nest://menu-badge/refresh',
    active: true,
    note: 'Refreshes live badge counts from QAD ODB. Disable only if QAD ODB is causing issues.',
  },
  {
    id: 'graphics-due-today-report',
    name: 'Graphics Due Today Report',
    cron: '30 22 * * *',
    url: 'nest://graphics-production/getDueTodayReport',
    active: false,
    note: 'Disabled',
  },
  {
    id: 'dashboard-performance',
    name: 'Dashboard Performance',
    cron: '*/30 * * * *',
    url: 'nest://scheduled-jobs/dashboard-performance',
    active: false,
    note: 'Disabled',
  },
  {
    id: 'dropin-workorder-emails',
    name: 'Drop-in Work Order Emails',
    cron: '*/30 * * * 1-5',
    url: 'nest://scheduled-jobs/dropin-workorder-emails',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'clean-users',
    name: 'Clean Users',
    cron: '*/6 * * * *',
    url: 'nest://scheduled-jobs/clean-users',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'total-shipped-orders',
    name: 'Total Shipped Orders',
    cron: '0 16 * * 1-5',
    url: 'nest://scheduled-jobs/total-shipped-orders',
    active: false,
    note: 'Disabled',
  },
  {
    id: 'overdue-orders',
    name: 'Overdue Orders',
    cron: '0 4 * * 1-5',
    url: 'nest://scheduled-jobs/overdue-orders',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'field-service-old-workorders',
    name: 'Field Service Old Work Orders',
    cron: '0 9 * * * 1-5',
    url: 'nest://scheduled-jobs/field-service-old-workorders',
    active: false,
    note: 'Disabled',
  },
  {
    id: 'open-shipping-requests',
    name: 'Open Shipping Requests',
    cron: '* * * * *',
    url: 'nest://scheduled-jobs/open-shipping-requests',
    active: false,
    note: 'Disabled',
  },
  {
    id: 'graphics-work-order',
    name: 'Graphics Work Order',
    cron: '*/20 * * * *',
    url: 'nest://scheduled-jobs/graphics-work-order',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'vehicle-expiration-email',
    name: 'Vehicle Expiration Email',
    cron: '0 7 * * *',
    url: 'nest://scheduled-jobs/vehicle-expiration-email',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'daily-report-insert',
    name: 'Daily Report Insert',
    cron: '0 16 * * 1-5',
    url: 'nest://scheduled-jobs/daily-report-insert',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'completed-production-orders',
    name: 'Completed Production Orders',
    cron: '0 4 * * 1-5',
    url: 'nest://scheduled-jobs/completed-production-orders',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'inspection-email',
    name: 'Inspection Email',
    cron: '0 14 * * 1-5',
    url: 'nest://scheduled-jobs/inspection-email',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'fs-job-report-morning',
    name: 'FS Job Report (Morning)',
    cron: '0 4 * * 1-5',
    url: 'nest://scheduled-jobs/fs-job-report-morning',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'fs-job-report-evening',
    name: 'FS Job Report (Evening)',
    cron: '0 17 * * 1-5',
    url: 'nest://scheduled-jobs/fs-job-report-evening',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'past-due-field-service-requests',
    name: 'Past Due Field Service Requests',
    cron: '0 6 * * 1-5',
    url: 'nest://scheduled-jobs/past-due-field-service-requests',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'lnw-delivery',
    name: 'LNW Delivery',
    cron: '0 7 * * 1-5',
    url: 'nest://scheduled-jobs/lnw-delivery',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'fs-job-notice',
    name: 'FS Job Notice',
    cron: '0 4 * * 1-5',
    url: 'nest://scheduled-jobs/fs-job-notice',
    active: false,
    note: 'Disabled - enable from UX',
  },
  {
    id: 'serial-stock-alert',
    name: 'Serial Stock Alert',
    cron: '0 7 * * *',
    url: 'nest://scheduled-jobs/serial-stock-alert',
    active: true,
    note: 'Daily 7 AM PT — emails serial_stock_alert recipients when any pool is at or below threshold.',
  },
  {
    id: 'overdue-qir',
    name: 'Overdue Quality Incidents',
    cron: '0 9 * * 1-5',
    url: 'nest://scheduled-jobs/overdue-qir',
    active: false,
    note: 'Action Required report for open quality incidents older than 7 days.',
  },
  {
    id: 'overdue-safety-incident',
    name: 'Overdue Safety Incidents',
    cron: '0 9 * * 1-5',
    url: 'nest://scheduled-jobs/overdue-safety-incident',
    active: false,
    note: 'Urgent action-needed report for open safety incidents older than 7 days.',
  },
  {
    id: 'inspection-checklist-report-generator',
    name: 'Inspection Checklist Report Generator',
    cron: '*/30 * * * * *',
    url: 'nest://scheduled-jobs/inspection-checklist-report-generator',
    active: true,
    note: 'Processes queued final-submission PDF jobs for submitted inspection checklists every 30 seconds.',
  },
  {
    id: 'open-checklist-instances-last-3-days',
    name: 'Open Checklist Instances (Older Than 3 Days)',
    cron: '0 0 8 * * *',
    url: 'nest://scheduled-jobs/open-checklist-instances-last-3-days',
    active: true,
    note: 'Scans for open checklist instances older than 3 days and sends an email report.',
  },
];
