import { ScheduledJobId } from './scheduled-job-ids';

export interface ScheduledJobDefinition {
  id: ScheduledJobId;
  name: string;
  cron: string;
  url: string;
  active: boolean;
  note?: string;
  supportsRecipients?: boolean;
}

export const SCHEDULED_JOBS_TIMEZONE = 'America/Los_Angeles';

export const SCHEDULED_JOB_DEFINITIONS: ScheduledJobDefinition[] = [
  {
    id: 'menu-badge-cache-refresh',
    name: 'Menu Badge Cache Refresh',
    cron: '0 0 * * * *',
    url: 'nest://menu-badge/refresh',
    active: true,
    note: 'System job. Refreshes live menu badge counts from QAD ODB. No email subscription is used for this job.',
    supportsRecipients: false,
  },
  {
    id: 'graphics-due-today-report',
    name: 'Graphics Due Today Email Report',
    cron: '30 22 * * *',
    url: 'nest://graphics-production/getDueTodayReport',
    active: false,
    note: 'Sends a daily report for graphics work orders due today. Subscribers receive the email report.',
  },
  {
    id: 'dashboard-performance',
    name: 'Dashboard Performance',
    cron: '*/30 * * * *',
    url: 'nest://scheduled-jobs/dashboard-performance',
    active: false,
    note: 'System job. Caches dashboard performance metrics. No email subscription is used for this job.',
    supportsRecipients: false,
  },
  {
    id: 'dropin-workorder-emails',
    name: 'Drop-in Work Order Notifications',
    cron: '*/30 * * * 1-5',
    url: 'nest://scheduled-jobs/dropin-workorder-emails',
    active: false,
    note: 'Sends notifications for drop-in work orders. Subscribers receive the email notifications.',
  },
  {
    id: 'clean-users',
    name: 'Clean Users',
    cron: '*/6 * * * *',
    url: 'nest://scheduled-jobs/clean-users',
    active: false,
    note: 'System maintenance job that normalizes user data. No email subscription is used for this job.',
    supportsRecipients: false,
  },
  {
    id: 'total-shipped-orders',
    name: 'Daily Shipping Summary',
    cron: '0 16 * * 1-5',
    url: 'nest://scheduled-jobs/total-shipped-orders',
    active: false,
    note: 'Sends a daily shipping summary. Subscribers receive the shipping report email.',
  },
  {
    id: 'overdue-orders',
    name: 'Overdue Operations Orders',
    cron: '0 4 * * 1-5',
    url: 'nest://scheduled-jobs/overdue-orders',
    active: false,
    note: 'Sends a report for overdue routing, shipping, and graphics orders. Subscribers receive the email report.',
  },
  {
    id: 'field-service-old-workorders',
    name: 'Field Service Old Work Orders',
    cron: '0 9 * * * 1-5',
    url: 'nest://scheduled-jobs/field-service-old-workorders',
    active: false,
    note: 'Sends a report of open field service work orders older than threshold. Subscribers receive the email report.',
  },
  {
    id: 'open-shipping-requests',
    name: 'Overdue Shipping Requests',
    cron: '* * * * *',
    url: 'nest://scheduled-jobs/open-shipping-requests',
    active: false,
    note: 'Sends alerts for open shipping requests older than 7 days. Subscribers receive the email alert.',
  },
  {
    id: 'graphics-work-order',
    name: 'Graphics Work Order',
    cron: '*/20 * * * *',
    url: 'nest://scheduled-jobs/graphics-work-order',
    active: false,
    note: 'Processes graphics work order automation. No email subscription is used for this job.',
  },
  {
    id: 'vehicle-expiration-email',
    name: 'Vehicle Expiration Email',
    cron: '0 7 * * *',
    url: 'nest://scheduled-jobs/vehicle-expiration-email',
    active: false,
    note: 'Sends registration expiration reminders for active vehicles. Subscribers receive the reminder emails.',
  },
  {
    id: 'daily-report-insert',
    name: 'Daily Report Insert',
    cron: '0 16 * * 1-5',
    url: 'nest://scheduled-jobs/daily-report-insert',
    active: false,
    note: 'System job that prepares daily reporting data. No email subscription is used for this job.',
    supportsRecipients: false,
  },
  {
    id: 'completed-production-orders',
    name: 'Production Work Order Status Report',
    cron: '0 4 * * 1-5',
    url: 'nest://scheduled-jobs/completed-production-orders',
    active: false,
    note: 'Sends a work-order status report for completed and over-completed production orders. Subscribers receive the email report.',
  },
  {
    id: 'inspection-email',
    name: 'Daily Inspection Summary',
    cron: '0 14 * * 1-5',
    url: 'nest://scheduled-jobs/inspection-email',
    active: false,
    note: 'Sends daily forklift and vehicle inspection summary results. Subscribers receive the summary email.',
  },
  {
    id: 'fs-job-report',
    name: 'Field Service Job Report',
    cron: '0 4,17 * * 1-5',
    url: 'nest://scheduled-jobs/fs-job-report',
    active: false,
    note: 'Sends Field Service scheduling reports at 4:00 AM and 5:00 PM (Mon-Fri) with CSV attachment. Subscribers receive the report email.',
  },
  {
    id: 'past-due-field-service-requests',
    name: 'Past Due Field Service Requests',
    cron: '0 6 * * 1-5',
    url: 'nest://scheduled-jobs/past-due-field-service-requests',
    active: false,
    note: 'Sends alerts for unscheduled Field Service requests older than 3 days. Subscribers receive the alert email.',
  },
  {
    id: 'lnw-delivery',
    name: 'LNW Delivery Schedule Report',
    cron: '0 7 * * 1-5',
    url: 'nest://scheduled-jobs/lnw-delivery',
    active: false,
    note: 'Sends upcoming LNW delivery schedule reports. Subscribers receive the delivery email report.',
  },
  {
    id: 'fs-job-notice',
    name: 'Field Service Appointment Notices',
    cron: '0 4 * * 1-5',
    url: 'nest://scheduled-jobs/fs-job-notice',
    active: false,
    note: 'Sends appointment notices to requestors and sends a daily summary to subscribers.',
  },
  {
    id: 'serial-stock-alert',
    name: 'Serial Inventory Threshold Alert',
    cron: '0 7 * * *',
    url: 'nest://scheduled-jobs/serial-stock-alert',
    active: true,
    note: 'Daily 7 AM PT alert when any serial pool is at or below threshold. Subscribers receive the alert email.',
  },
  {
    id: 'overdue-qir',
    name: 'Overdue Quality Incidents',
    cron: '0 9 * * 1-5',
    url: 'nest://scheduled-jobs/overdue-qir',
    active: false,
    note: 'Sends an action-required report for open quality incidents older than 7 days. Subscribers receive the report email.',
  },
  {
    id: 'overdue-safety-incident',
    name: 'Overdue Safety Incidents',
    cron: '0 9 * * 1-5',
    url: 'nest://scheduled-jobs/overdue-safety-incident',
    active: false,
    note: 'Sends an urgent action-needed report for open safety incidents older than 7 days. Subscribers receive the report email.',
  },
  {
    id: 'inspection-checklist-report-generator',
    name: 'Inspection Checklist Report Generator',
    cron: '*/30 * * * * *',
    url: 'nest://scheduled-jobs/inspection-checklist-report-generator',
    active: true,
    note: 'System job that generates queued final-submission PDFs every 30 seconds. No email subscription is used for this job.',
  },
  {
    id: 'open-checklist-instances-last-3-days',
    name: 'Open Checklist Instances (Older Than 3 Days)',
    cron: '0 0 8 * * *',
    url: 'nest://scheduled-jobs/open-checklist-instances-last-3-days',
    active: true,
    note: 'Sends a daily report of open checklist instances older than 3 days. Subscribers receive the report email.',
  },
];
