export const MENU_DATA = {
  "table": "menu",
  "rows": [
    {
      "id": 245,
      "parent_id": null,
      "label": "UL Label",
      "icon": null,
      "link": "/dashboard/ul-management/v3",
      "description": null,
      "isCollapsed": null,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 244,
      "parent_id": 160,
      "label": "Serial Number Report",
      "icon": null,
      "link": "/dashboard/quality/serial-number-report",
      "description": null,
      "isCollapsed": null,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 243,
      "parent_id": 160,
      "label": "Serial Number Generator",
      "icon": null,
      "link": "/dashboard/quality/serial-number-generator",
      "description": null,
      "isCollapsed": null,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 242,
      "parent_id": 160,
      "label": "Version Control",
      "icon": null,
      "link": "/dashboard/quality/version-control",
      "description": null,
      "isCollapsed": null,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 230,
      "parent_id": 224,
      "label": "Serial Loader",
      "icon": null,
      "link": "/dashboard/quality/igt/serial-manager",
      "description": null,
      "isCollapsed": null,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 227,
      "parent_id": 224,
      "label": "List IGT",
      "icon": null,
      "link": "/dashboard/quality/igt/list",
      "description": null,
      "isCollapsed": null,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 226,
      "parent_id": 224,
      "label": "Create IGT Serial",
      "icon": null,
      "link": "/dashboard/quality/igt/create",
      "description": null,
      "isCollapsed": null,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 225,
      "parent_id": 224,
      "label": "Edit IGT",
      "icon": null,
      "link": "/dashboard/quality/igt/edit",
      "description": null,
      "isCollapsed": null,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 246,
      "parent_id": 224,
      "label": "Manage Existing IGT Serials",
      "icon": null,
      "link": "/dashboard/quality/igt/manage-existing",
      "description": null,
      "isCollapsed": null,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 224,
      "parent_id": 231,
      "label": "IGT Serials",
      "icon": "las la-tachometer-alt",
      "link": null,
      "description": null,
      "isCollapsed": 1,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 231,
      "parent_id": 160,
      "label": "Serial Management",
      "icon": "las la-tachometer-alt",
      "link": null,
      "description": null,
      "isCollapsed": 1,
      "accessRequired": 0,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": null
    },
    {
      "id": 160,
      "parent_id": 0,
      "label": "Quality",
      "icon": "las la-tools",
      "link": null,
      "description": null,
      "isCollapsed": 1,
      "accessRequired": 1,
      "badge": null,
      "isTitle": null,
      "hideCheckBox": null,
      "active": 1,
      "seq": 4
    }
  ]
};