<?php

/**
 * Undocumented class
 * As we discussed last week – we need to start working on a new EYEFI Asset Number. Here are some of the requirements: 
 *	A product will be getting either EYEFI ASSET number ( New) or EYEFI Serial Tag ( Already existing and implemented on the dashboard)
 *	The asset number should be generated by the dashboard , format as follows: YYYYMMDDXXX ( where xxx is a sequential number for the day), e.g. 20251105001, should be unique same as for the tags
 *	We should be able to assign different quantities per WO – e.g. 1,2, 3….
 *	This can be also for each customer, same process should follow as for the normal EYEFI tag ( UL, customer asset tag, printing,,,)+
 */
class EyefiAssetGenerator
{

    protected $db;
    public $user_full_name;
    public $nowDate;

    public function __construct($db)
    {

        $this->db = $db;
        $this->nowDate = date("Y-m-d H:i:s", time());
    }

    public function getWeekNumber($date)
    {
        $ddate = $date;
        $date = new DateTime($ddate);
        return $date->format("W");
    }

    public function getYearNumber($date)
    {
        $ddate = $date;
        $date = new DateTime($ddate);
        return $date->format("Y");
    }

    public function generateSerialNumber($previous_sequence, $currentDateNumber, $lastRecordedYearNumber)
    {

        //set values
        $curretDate = date("ymd");
        $sequence = '001';

        if ($currentDateNumber == $currentDateNumber) {
            $sequence = str_pad($previous_sequence + 1, 2, "0", STR_PAD_LEFT);
        }

        //standard
        return $curretDate . $sequence;
    }

    public function addNew($data)
    {

        $mainQry = "
            select RIGHT(asset_number, 2) asset_number,
                id, 
                date(time_stamp) dateCreated
            from eyefidb.eyefiAssetGenerator
            ORDER BY id DESC
            LIMIT 1
        ";
        $query = $this->db->prepare($mainQry);
        $query->execute();
        $result = $query->fetch();

        if(ISSET($data['asset_number']) && $data['asset_number'] != ''){
            $eyefiAssetNumber = $data['asset_number'];
        }else{

            $lastRecordedWeekNumber = $this->getWeekNumber($result['dateCreated']);
            $lastRecordedYearNumber = $this->getYearNumber($result['dateCreated']);

            $eyefiAssetNumber = $this->generateSerialNumber($result['asset_number'], $lastRecordedWeekNumber, $lastRecordedYearNumber);

        }

        $mainQry = "
				INSERT INTO eyefidb.eyefiAssetGenerator (
					time_stamp
					, asset_number
                    , active
				) VALUES (
					now()
					, :asset_number
                    , now()
                    , active:1
				)
			";

        $query = $this->db->prepare($mainQry);
        $query->bindParam(':asset_number', $data['asset_number'], PDO::PARAM_STR);
        $query->execute();
        return $eyefiAssetNumber;
    }

    public function delete($data)
    {
        $mainQry = "
            UPDATE eyefidb.eyefiAssetGenerator
                SET active = :active
            WHERE id = :id	
        ";
        $query = $this->db->prepare($mainQry);
        $query->bindParam(':active', $data['active'], PDO::PARAM_INT);
        $query->bindParam(':id', $data['id'], PDO::PARAM_INT);
        $query->execute();
    }

    public function edit($data)
    {

        $mainQry = "
				UPDATE eyefidb.eyefiAssetGenerator
					SET lastUpdate = :lastUpdate
				WHERE id = :id	
			";

        $query = $this->db->prepare($mainQry);
        $query->bindParam(':lastUpdate', $this->nowDate, PDO::PARAM_STR);
        $query->bindParam(':id', $data['id'], PDO::PARAM_INT);
        $query->execute();
    }


    public function readAll()
    {

        $mainQry = "
				select id 
					, time_stamp
					, asset_number
				from eyefidb.eyefiAssetGenerator
                where active = 1
				ORDER BY timeStamp DESC
			";

        $query = $this->db->prepare($mainQry);
        $query->execute();
        $result = $query->fetchAll(PDO::FETCH_ASSOC);

        return $result;
    }


    /**
     * Undocumented function
     *
     * @param [type] $id
     * @return void
     * get the id of the asset number
     */
    public function getById($id)
    {

        $mainQry = "
				select a.*
				from eyefidb.eyefiAssetGenerator a
                where id = :id
				ORDER BY timeStamp DESC
			";

        $query = $this->db->prepare($mainQry);
        $query->bindParam(':id', $id, PDO::PARAM_INT);
        $query->execute();
        $result = $query->fetch(PDO::FETCH_ASSOC);

        return $result;
    }
}
